#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'build-essential'
cookbook 'apt'
cookbook 'sudo'
cookbook 'git'

cookbook 'jenkins', git: 'https://github.com/fnichol/chef-jenkins'

